# Generated by Django 5.0.1 on 2024-03-22 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_remove_profile_address_remove_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardinghouse',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Website.profile'),
        ),
    ]
