# Generated by Django 5.0.1 on 2024-03-22 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_boardinghouse_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinghouse',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Website.profile'),
        ),
    ]
