# Generated by Django 5.0.1 on 2024-03-22 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_alter_boardinghouse_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardinghouse',
            name='profile',
        ),
    ]
