# Generated by Django 5.0.1 on 2024-03-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0007_remove_boardinghouse_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='owner_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
