# Generated by Django 5.0.1 on 2024-03-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0009_alter_booking_boarding_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
