# Generated by Django 5.0.1 on 2024-04-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0012_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='chip_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='CHIPID'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='weight',
            field=models.FloatField(verbose_name="Dog's weight"),
        ),
    ]
