# Generated by Django 5.0.1 on 2024-04-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0013_alter_dog_chip_id_alter_dog_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='dog_name',
            new_name='name',
        ),
    ]
