# Generated by Django 5.0.1 on 2024-04-09 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0014_rename_dog_name_dog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Website.dog'),
        ),
    ]
