# Generated by Django 5.0.1 on 2024-04-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0015_booking_dog'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardinghouse',
            name='map_location',
            field=models.URLField(blank=True, null=True),
        ),
    ]
